version: '3.8'

services:
  backend:
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
      - "5678:5678"  # Debugger port
    environment:
      DATABASE_URL: postgresql://stockuser:stockpass123@database:5432/stock_analyzer
      PYTHONUNBUFFERED: 1
