"""add last_fetch_at and next_fetch_at to stocks

Revision ID: e29f036ebfa7
Revises: 198a0e1e4d5f
Create Date: 2025-10-31 16:34:11.688152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29f036ebfa7'
down_revision: Union[str, Sequence[str], None] = '198a0e1e4d5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_dividends_frequency', table_name='dividends')
    op.drop_index('idx_dividends_payment_date', table_name='dividends')
    op.drop_index('idx_news_sentiment', table_name='news')
    op.drop_index('idx_news_stock_published', table_name='news')
    op.drop_table_comment(
        'prediction_performance',
        existing_comment='Tracks accuracy of predictions vs actual results',
        schema=None
    )
    op.drop_index('idx_predictions_stock_id', table_name='predictions')
    op.drop_index('idx_predictions_target_date', table_name='predictions')
    op.create_foreign_key(None, 'predictions', 'stocks', ['stock_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'predictions',
        existing_comment='ML model predictions for stock prices',
        schema=None
    )
    op.drop_index('idx_sentiment_scores_stock_id', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_scores_timestamp', table_name='sentiment_scores')
    op.create_foreign_key(None, 'sentiment_scores', 'stocks', ['stock_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'sentiment_scores',
        existing_comment='Stores news sentiment analysis results using FinBERT',
        schema=None
    )
    op.drop_index('idx_short_interest_settlement', table_name='short_interest')
    op.drop_index('idx_splits_execution_date', table_name='stock_splits')
    op.add_column('stocks', sa.Column('last_fetch_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('stocks', sa.Column('next_fetch_at', sa.TIMESTAMP(), nullable=True))
    op.drop_index('idx_stocks_priority', table_name='stocks')
    op.drop_index('idx_technical_indicators_stock_timestamp', table_name='technical_indicators')
    op.drop_constraint('technical_indicators_stock_id_timestamp_indicator_name_key', 'technical_indicators', type_='unique')
    op.create_foreign_key(None, 'technical_indicators', 'stocks', ['stock_id'], ['id'], ondelete='CASCADE')
    op.drop_table_comment(
        'technical_indicators',
        existing_comment='Stores calculated technical indicator values',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'technical_indicators',
        'Stores calculated technical indicator values',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'technical_indicators', type_='foreignkey')
    op.create_unique_constraint('technical_indicators_stock_id_timestamp_indicator_name_key', 'technical_indicators', ['stock_id', 'timestamp', 'indicator_name'])
    op.create_index('idx_technical_indicators_stock_timestamp', 'technical_indicators', ['stock_id', 'timestamp'], unique=False)
    op.create_index('idx_stocks_priority', 'stocks', ['priority', 'is_tracked'], unique=False)
    op.drop_column('stocks', 'next_fetch_at')
    op.drop_column('stocks', 'last_fetch_at')
    op.create_index('idx_splits_execution_date', 'stock_splits', ['execution_date'], unique=False)
    op.create_index('idx_short_interest_settlement', 'short_interest', ['settlement_date'], unique=False)
    op.create_table_comment(
        'sentiment_scores',
        'Stores news sentiment analysis results using FinBERT',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'sentiment_scores', type_='foreignkey')
    op.create_index('idx_sentiment_scores_timestamp', 'sentiment_scores', ['timestamp'], unique=False)
    op.create_index('idx_sentiment_scores_stock_id', 'sentiment_scores', ['stock_id'], unique=False)
    op.create_table_comment(
        'predictions',
        'ML model predictions for stock prices',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'predictions', type_='foreignkey')
    op.create_index('idx_predictions_target_date', 'predictions', ['target_date'], unique=False)
    op.create_index('idx_predictions_stock_id', 'predictions', ['stock_id'], unique=False)
    op.create_table_comment(
        'prediction_performance',
        'Tracks accuracy of predictions vs actual results',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_news_stock_published', 'news', ['stock_id', 'published_utc'], unique=False)
    op.create_index('idx_news_sentiment', 'news', ['sentiment'], unique=False)
    op.create_index('idx_dividends_payment_date', 'dividends', ['payment_date'], unique=False)
    op.create_index('idx_dividends_frequency', 'dividends', ['frequency'], unique=False)
    # ### end Alembic commands ###
